### PR TITLE
fixed header, style

### PR DESCRIPTION
**Pull request by NybergViktor**
done:

Fixed styling and function, slides in from the side and looks a lot better than before.

what to check:

responsive design etc

### CODE REVIEW

**Comment by TommyDahlin** [comment]
dropdown menu Border onHover looks WHACK
dropdown register/sign in box does weird stuff before the menu goes from the left

**Comment by NybergViktor** [comment]
gjorde om hela, nu är den bra igen

**Review by johnsson84 — CHANGES_REQUESTED** [review]
Desktop, no fullscreen menu

**Comment by NybergViktor** [comment]
Fixed hover on button.
Fixed styling on desktop.
Added a shake animation at hovering on desktop

**Review by johnsson84 — APPROVED** [review]
Blir bra!

**Pull request merged**
